### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by TeodorBankov** [TeodorBankov/dobrovoltsi-bg#6]
0. JWT - да се провери дали всичко работи точно
1. Съпорт за снимки в базата данни
2. Съпорт за едитване на профила
3. Съпорт за смяна на пароли, триене на профили и тн... (да се допълни)
4. Профилна снимка 
5. Профил връзки (?)
6. Проверка с документацията
6.1 АДМИН РОЛЯ(!!!) 
6.2 одобряване на инициативите
6.3 админа да може да трие всичките профили и кандидатури и тн (съгласувайте се с документацията)

7. Изпипване на инициативите:
7.1 Добавка календар пикер
7.2 Добавка локация пикер (гугъл мапс)
7.3 добавка главна карта с всичките инициативи на предната страница
7.5 коментари под инициатива (в детайлите)

8. Изпипване на дизайна
8.1 Хубави анимации + плавен фронтенд (нисък приоритет)
8.2 избиране на цветова палитра и правене на сайта в съответната такава
8.3 избиране и качване на снимки, видеа и тн по страниците (нисък приоритет)

9. Тестване 
9.0 Ръчно тестване и намиране на бъгове (!!!!!!)
9.1 Планиране, обсъждане и първоначална интеграция на Автоматизирано тестване

10. Документация за групата, на която ще предадем проекта

Каквото се сетите или откриете, добавете в този коментар.

**Comment by TeodorBankov** [comment]
Намерен бъг при JWT - при логаут:

Uncaught runtime errors:
×
ERROR
Cannot read properties of null (reading 'role')
TypeError: Cannot read properties of null (reading 'role')
    at InitiativeList (http://localhost:3000/static/js/bundle.js:3268:30)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:32200:22)
    at updateFunctionComponent (http://localhost:3000/static/js/bundle.js:35767:24)
    at beginWork (http://localhost:3000/static/js/bundle.js:37486:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:22456:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:22500:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:22557:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:42455:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:41703:16)
    at workLoopSync (http://localhost:3000/static/js/bundle.js:41626:9)
ERROR
Cannot read properties of null (reading 'role')
TypeError: Cannot read properties of null (reading 'role')
    at InitiativeList (http://localhost:3000/static/js/bundle.js:3268:30)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:32200:22)
    at updateFunctionComponent (http://localhost:3000/static/js/bundle.js:35767:24)
    at beginWork (http://localhost:3000/static/js/bundle.js:37486:20)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:42433:18)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:41703:16)
    at workLoopSync (http://localhost:3000/static/js/bundle.js:41626:9)
    at renderRootSync (http://localhost:3000/static/js/bundle.js:41599:11)
    at performSyncWorkOnRoot (http://localhost:3000/static/js/bundle.js:41291:24)
    at flushSyncCallbacks (http://localhost:3000/static/js/bundle.js:29293:26)

**Comment by TeodorBankov** [comment]
Добавена роля администратор, и направен нов профил за администратора - email: administrator@dobrovoltsibg.com, pass: dobrovoltsibg

**Comment by TeodorBankov** [comment]
Качен е къмит [92dcf3c](https://github.com/TeodorBankov/dobrovoltsi-bg/commit/af66f361ddb1ebce918334f4f3224fe136dd8c87) по точки 0,1,2,3,4,5,6 по TODO-то.

**Comment by TeodorBankov** [comment]
Качен е къмит [6ea8e5e](https://github.com/TeodorBankov/dobrovoltsi-bg/commit/6ea8e5e7dbddee684ffa87c785aae9375578fe90) в дев бранча по точки 7.1 7.2 7.3 по TODO-то.

**Comment by TeodorBankov** [comment]
Оставащо TODO:

**!!!! Все още съществува някакъв проблем със сесията !!!! Да се види с НАЙ-ВИСОК приоритет !!!**

7.5 коментари под инициатива (в детайлите) 
7.6 Покриване на останали Edge Кейсове (Ако са останали такива) 
7.7 Трябва ли да има нещо в админския дашборд? Да се обсъди и да се внедри.

8. Изпипване на дизайна
8.0 Оправяне на дизайна на картата по екраните и страниците
8.1 Плавен фронтенд - намиране и оправяне на останали бъгове 
8.2 Обсъждане на финални щрихи и функционалност.
8.3 Финални оптимизации на процесите и изчистване на кода

9. Създаване на документация

9. Тестване
9.0 Ръчно тестване и намиране на бъгове (!!!!!!)
9.1 Планиране, обсъждане и първоначална интеграция на Автоматизирано тестване
9.2 Оправяне на бъгове след автоматизирани тестове(?) Да се съгласува с условията на курсовата

10. Мърджване на кода в мейн бранча

за момента се сещам поне за един едж кейс по 7.6 - при липса на каквито и да е събития или кандидатури да се хандълне подобаващо във фронтенда, да се изписва на потребителя.

**Comment by TeodorBankov** [comment]
Хубаво ще е да се започне също документацията със сегашната база код и да се надгражда.

**Comment by TeodorBankov** [comment]
Качен е къмит [54eed0f](https://github.com/TeodorBankov/dobrovoltsi-bg/commit/54eed0ff6664380db7d05b53bcf432deea89c864) по точки 7.5 по TODO-то.

**Comment by TeodorBankov** [comment]
Качен е къмит [840e127](https://github.com/TeodorBankov/dobrovoltsi-bg/commit/840e127a3fa53d2c5b34b8a7442d57c3cf2f9b07) по точки 0, 7.7 по TODO-то.

**Comment by TeodorBankov** [comment]
Оставащо TODO:

7.6 Покриване на останали Edge Кейсове (Ако са останали такива)

8. Изпипване на дизайна
8.1 Плавен фронтенд - намиране и оправяне на останали бъгове
8.2 Обсъждане на финални щрихи и функционалност.
8.3 Финални оптимизации на процесите и изчистване на кода

9. Създаване на документация

10. Тестване
10.1 Прочитане на лекцията за тестове, и създаване на схема от там нататък.

11. Мърджване на кода в мейн бранча

**Comment by TeodorBankov** [comment]
Качен е къмит [06bb90f](https://github.com/TeodorBankov/dobrovoltsi-bg/commit/06bb90f8a1bae0c94bf2dc7ddc9cda7391066b24) по точки 7.6, 8 - 8.1, 8.2, 8.3

**Comment by TeodorBankov** [comment]
Качен е къмит [95f0883](https://github.com/TeodorBankov/dobrovoltsi-bg/commit/95f0883da2a41d8367cc9a259fed9718fa9aad46) с документацията от точка 9. остава да се рафинира документацията, тестване и мърджване на кода в мейн бранча след тестовете.

**Comment by TeodorBankov** [comment]
Добавени са тестовите случаи, проведени тестове и бранча dev е мърджнат в main.
